{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/graffiti\/kdefault_xattr_delim"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/graffiti\/kdefault_xattr_delim"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/kDEFAULT_XATTR_DELIM","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"kDEFAULT_XATTR_DELIM","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:XattrBridge.h@kDEFAULT_XATTR_DELIM","modules":[{"name":"Graffiti"}],"navigatorTitle":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}]},"hierarchy":{"paths":[["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti"]]},"references":{"doc://com.tom.Graffiti/documentation/Graffiti/kDEFAULT_XATTR_DELIM":{"role":"symbol","title":"kDEFAULT_XATTR_DELIM","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/kDEFAULT_XATTR_DELIM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}],"url":"\/documentation\/graffiti\/kdefault_xattr_delim"},"doc://com.tom.Graffiti/documentation/Graffiti":{"role":"collection","title":"Graffiti","abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","kind":"symbol","type":"topic","url":"\/documentation\/graffiti"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"kDEFAULT_XATTR_DELIM"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1kDEFAULT_XATTR_DELIM\/title","value":"kDEFAULT_XATTR_DELIM"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1kDEFAULT_XATTR_DELIM\/fragments","value":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}