{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/graffiti\/xattrbridge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/graffiti\/xattrbridge"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.tom.Graffiti\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.tom.Graffiti\/objc(pl)NSObject","doc:\/\/com.tom.Graffiti\/s7CVarArgP","doc:\/\/com.tom.Graffiti\/s28CustomDebugStringConvertibleP","doc:\/\/com.tom.Graffiti\/s23CustomStringConvertibleP","doc:\/\/com.tom.Graffiti\/SQ","doc:\/\/com.tom.Graffiti\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttribute(forFile:withKey:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/removeXAttrAttributes(forFile:withKey:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/setXAttrAttributeForFile(_:valueOf:withKey:andError:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"title":"XattrBridge","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)XattrBridge","modules":[{"name":"Graffiti"}],"navigatorTitle":[{"kind":"identifier","text":"XattrBridge"}]},"hierarchy":{"paths":[["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti"]]},"references":{"doc://com.tom.Graffiti/documentation/Graffiti":{"role":"collection","title":"Graffiti","abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","kind":"symbol","type":"topic","url":"\/documentation\/graffiti"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/removeXAttrAttributes(forFile:withKey:andError:)":{"role":"symbol","title":"removeXAttrAttributes(forFile:withKey:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeXAttrAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/removeXAttrAttributes(forFile:withKey:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeXAttrAttributesForFile:withKey:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/removexattrattributes(forfile:withkey:anderror:)"},"doc://com.tom.Graffiti/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.tom.Graffiti\/objc(cs)NSObject"},"doc://com.tom.Graffiti/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.tom.Graffiti\/SH"},"doc://com.tom.Graffiti/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.tom.Graffiti\/s28CustomDebugStringConvertibleP"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/getXAttrAttribute(forFile:withKey:andError:)":{"role":"symbol","title":"getXAttrAttribute(forFile:withKey:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getXAttrAttribute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttribute(forFile:withKey:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getXAttrAttributeForFile:withKey:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/getxattrattribute(forfile:withkey:anderror:)"},"doc://com.tom.Graffiti/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.tom.Graffiti\/SQ"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)":{"role":"symbol","title":"getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getXAttrAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delimitedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/getxattrattributes(forfile:withkey:delimitedby:anderror:)"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge":{"role":"symbol","title":"XattrBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XattrBridge"}],"url":"\/documentation\/graffiti\/xattrbridge"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)":{"role":"symbol","title":"appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"appendXAttrAttribute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delimitedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"appendXAttrAttributeForFile:valueOf:withKey:delimitedBy:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/appendxattrattribute(forfile:valueof:withkey:delimitedby:anderror:)"},"doc://com.tom.Graffiti/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.tom.Graffiti\/objc(pl)NSObject"},"doc://com.tom.Graffiti/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.tom.Graffiti\/s7CVarArgP"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/setXAttrAttributeForFile(_:valueOf:withKey:andError:)":{"role":"symbol","title":"setXAttrAttributeForFile(_:valueOf:withKey:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setXAttrAttributeForFile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/setXAttrAttributeForFile(_:valueOf:withKey:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/setxattrattributeforfile(_:valueof:withkey:anderror:)"},"doc://com.tom.Graffiti/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.tom.Graffiti\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"XattrBridge"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"XattrBridge"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"XattrBridge"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttribute(forFile:withKey:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/removeXAttrAttributes(forFile:withKey:andError:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/setXAttrAttributeForFile(_:valueOf:withKey:andError:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.tom.Graffiti\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1removeXAttrAttributes(forFile:withKey:andError:)\/title","value":"removeXAttrAttributesForFile:withKey:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1removeXAttrAttributes(forFile:withKey:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"removeXAttrAttributesForFile:withKey:andError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttribute(forFile:withKey:andError:)\/title","value":"getXAttrAttributeForFile:withKey:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttribute(forFile:withKey:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getXAttrAttributeForFile:withKey:andError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttributes(forFile:withKey:delimitedBy:andError:)\/title","value":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttributes(forFile:withKey:delimitedBy:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/title","value":"XattrBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/fragments","value":[{"kind":"identifier","text":"XattrBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)\/title","value":"appendXAttrAttributeForFile:valueOf:withKey:delimitedBy:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1appendXAttrAttribute(forFile:valueOf:withKey:delimitedBy:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"appendXAttrAttributeForFile:valueOf:withKey:delimitedBy:andError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1setXAttrAttributeForFile(_:valueOf:withKey:andError:)\/title","value":"setXAttrAttributeForFile:valueOf:withKey:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1setXAttrAttributeForFile(_:valueOf:withKey:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}