{"variants":[{"paths":["\/documentation\/graffiti"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/graffiti"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AddTagToManyFilesTransaction","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AddTagTransaction","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AnySelectionModel","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ApplicationState","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/CompressedCustomTagStoreWriter","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileTagBackend","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ImageTextContent","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/JSONFileWriter","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2Input","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2Output","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/RemoveTagFromManyFilesTransaction","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/RemoveTagTransaction","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Sorter","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Tag","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TaggedDirectory","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TaggedFile","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge"]},{"title":"Protocols","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AnyOptional","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileWriter","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagBackend","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagTransaction"]},{"title":"Structures","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ContentView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ContentView_Previews","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ConvertView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FilesEditingInspectorView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FormatOption","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FormatSelector","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/GraffitiApp","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ImageSelector","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MainView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/SettingsView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/SettingsView_Previews","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagStore","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagView","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Version"]},{"title":"Variables","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/bookmarksPath","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/kDEFAULT_XATTR_DELIM"]},{"title":"Functions","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TPData(contentsOf:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/accessBookmark(of:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/convert(file:isUsing:willUse:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/createOwnedImageURL()","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/getContentsOfDirectory(atPath:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/getSandboxedAccess(to:thenPerform:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/jsonify(tag:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/loadDefaultSettings(from:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/os_log(_:log:type:_:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/saveBookmark(of:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/selectFile(ofTypes:callback:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/selectFolder(callback:)","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/takeOwnership(of:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AppState","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileError","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileWriterError","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Format","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Log","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Type"]}],"kind":"symbol","metadata":{"roleHeading":"Application","externalID":"Graffiti","title":"Graffiti","symbolKind":"module","role":"collection","modules":[{"name":"Graffiti"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.tom.Graffiti/documentation/Graffiti/ContentView_Previews":{"role":"symbol","title":"ContentView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentView_Previews"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ContentView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentView_Previews"}],"url":"\/documentation\/graffiti\/contentview_previews"},"doc://com.tom.Graffiti/documentation/Graffiti/getContentsOfDirectory(atPath:)":{"role":"symbol","title":"getContentsOfDirectory(atPath:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getContentsOfDirectory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"atPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/getContentsOfDirectory(atPath:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/getcontentsofdirectory(atpath:)"},"doc://com.tom.Graffiti/documentation/Graffiti/convert(file:isUsing:willUse:)":{"role":"symbol","title":"convert(file:isUsing:willUse:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convert"},{"kind":"text","text":"("},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isUsing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileWriter","preciseIdentifier":"s:8Graffiti10FileWriterP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willUse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileWriter","preciseIdentifier":"s:8Graffiti10FileWriterP"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/convert(file:isUsing:willUse:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/convert(file:isusing:willuse:)"},"doc://com.tom.Graffiti/documentation/Graffiti/getSandboxedAccess(to:thenPerform:)":{"role":"symbol","title":"getSandboxedAccess(to:thenPerform:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getSandboxedAccess"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"R"},{"kind":"text","text":">("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"thenPerform"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"R","preciseIdentifier":"s:8Graffiti18getSandboxedAccess2to11thenPerformxSS_xSSKXEtKlF1RL_xmfp"},{"kind":"text","text":")) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"R","preciseIdentifier":"s:8Graffiti18getSandboxedAccess2to11thenPerformxSS_xSSKXEtKlF1RL_xmfp"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/getSandboxedAccess(to:thenPerform:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/getsandboxedaccess(to:thenperform:)"},"doc://com.tom.Graffiti/documentation/Graffiti/MobileNetV2Output":{"role":"symbol","title":"MobileNetV2Output","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileNetV2Output"}],"abstract":[{"type":"text","text":"Model Prediction Output Type"}],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2Output","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileNetV2Output"}],"url":"\/documentation\/graffiti\/mobilenetv2output"},"doc://com.tom.Graffiti/documentation/Graffiti/FormatSelector":{"role":"symbol","title":"FormatSelector","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormatSelector"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FormatSelector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormatSelector"}],"url":"\/documentation\/graffiti\/formatselector"},"doc://com.tom.Graffiti/documentation/Graffiti/takeOwnership(of:)":{"role":"symbol","title":"takeOwnership(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"takeOwnership"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/takeOwnership(of:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/takeownership(of:)"},"doc://com.tom.Graffiti/documentation/Graffiti/RemoveTagFromManyFilesTransaction":{"role":"symbol","title":"RemoveTagFromManyFilesTransaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoveTagFromManyFilesTransaction"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/RemoveTagFromManyFilesTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoveTagFromManyFilesTransaction"}],"url":"\/documentation\/graffiti\/removetagfrommanyfilestransaction"},"doc://com.tom.Graffiti/documentation/Graffiti/AnySelectionModel":{"role":"symbol","title":"AnySelectionModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnySelectionModel"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AnySelectionModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnySelectionModel"}],"url":"\/documentation\/graffiti\/anyselectionmodel"},"doc://com.tom.Graffiti/documentation/Graffiti/loadDefaultSettings(from:)":{"role":"symbol","title":"loadDefaultSettings(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadDefaultSettings"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ApplicationState","preciseIdentifier":"s:8Graffiti16ApplicationStateC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/loadDefaultSettings(from:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/loaddefaultsettings(from:)"},"doc://com.tom.Graffiti/documentation/Graffiti/SettingsView":{"role":"symbol","title":"SettingsView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/SettingsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsView"}],"url":"\/documentation\/graffiti\/settingsview"},"doc://com.tom.Graffiti/documentation/Graffiti/FileWriterError":{"role":"symbol","title":"FileWriterError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileWriterError"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileWriterError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileWriterError"}],"url":"\/documentation\/graffiti\/filewritererror"},"doc://com.tom.Graffiti/documentation/Graffiti/Format":{"role":"symbol","title":"Format","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Format"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Format","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Format"}],"url":"\/documentation\/graffiti\/format"},"doc://com.tom.Graffiti/documentation/Graffiti/TaggedDirectory":{"role":"symbol","title":"TaggedDirectory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaggedDirectory"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TaggedDirectory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TaggedDirectory"}],"url":"\/documentation\/graffiti\/taggeddirectory"},"doc://com.tom.Graffiti/documentation/Graffiti/FileError":{"role":"symbol","title":"FileError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileError"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileError"}],"url":"\/documentation\/graffiti\/fileerror"},"doc://com.tom.Graffiti/documentation/Graffiti/ImageTextContent":{"role":"symbol","title":"ImageTextContent","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageTextContent"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ImageTextContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageTextContent"}],"url":"\/documentation\/graffiti\/imagetextcontent"},"doc://com.tom.Graffiti/documentation/Graffiti/MainView":{"role":"symbol","title":"MainView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MainView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MainView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MainView"}],"url":"\/documentation\/graffiti\/mainview"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge":{"role":"symbol","title":"XattrBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XattrBridge"}],"url":"\/documentation\/graffiti\/xattrbridge"},"doc://com.tom.Graffiti/documentation/Graffiti/JSONFileWriter":{"role":"symbol","title":"JSONFileWriter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONFileWriter"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/JSONFileWriter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JSONFileWriter"}],"url":"\/documentation\/graffiti\/jsonfilewriter"},"doc://com.tom.Graffiti/documentation/Graffiti/accessBookmark(of:)":{"role":"symbol","title":"accessBookmark(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/accessBookmark(of:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/accessbookmark(of:)"},"doc://com.tom.Graffiti/documentation/Graffiti/FileTagBackend":{"role":"symbol","title":"FileTagBackend","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileTagBackend"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileTagBackend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileTagBackend"}],"url":"\/documentation\/graffiti\/filetagbackend"},"doc://com.tom.Graffiti/documentation/Graffiti/Version":{"role":"symbol","title":"Version","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Version"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Version","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Version"}],"url":"\/documentation\/graffiti\/version"},"doc://com.tom.Graffiti/documentation/Graffiti/TaggedFile":{"role":"symbol","title":"TaggedFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TaggedFile"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TaggedFile","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TaggedFile"}],"url":"\/documentation\/graffiti\/taggedfile"},"doc://com.tom.Graffiti/documentation/Graffiti/FilesEditingInspectorView":{"role":"symbol","title":"FilesEditingInspectorView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FilesEditingInspectorView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FilesEditingInspectorView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FilesEditingInspectorView"}],"url":"\/documentation\/graffiti\/fileseditinginspectorview"},"doc://com.tom.Graffiti/documentation/Graffiti/Tag":{"role":"symbol","title":"Tag","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Tag"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Tag"},{"type":"text","text":" class represents a "},{"type":"codeVoice","code":"String"},{"type":"text","text":" or an "},{"type":"codeVoice","code":"NSImage"},{"type":"text","text":" that tags a particular file"}],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Tag","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Tag"}],"url":"\/documentation\/graffiti\/tag"},"doc://com.tom.Graffiti/documentation/Graffiti/ImageSelector":{"role":"symbol","title":"ImageSelector","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSelector"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ImageSelector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSelector"}],"url":"\/documentation\/graffiti\/imageselector"},"doc://com.tom.Graffiti/documentation/Graffiti/saveBookmark(of:)":{"role":"symbol","title":"saveBookmark(of:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"saveBookmark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/saveBookmark(of:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/savebookmark(of:)"},"doc://com.tom.Graffiti/documentation/Graffiti/bookmarksPath":{"role":"symbol","title":"bookmarksPath","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bookmarksPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/bookmarksPath","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/bookmarkspath"},"doc://com.tom.Graffiti/documentation/Graffiti/ConvertView":{"role":"symbol","title":"ConvertView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConvertView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ConvertView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConvertView"}],"url":"\/documentation\/graffiti\/convertview"},"doc://com.tom.Graffiti/documentation/Graffiti/TagTransaction":{"role":"symbol","title":"TagTransaction","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagTransaction"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagTransaction"}],"url":"\/documentation\/graffiti\/tagtransaction"},"doc://com.tom.Graffiti/documentation/Graffiti/MobileNetV2":{"role":"symbol","title":"MobileNetV2","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileNetV2"}],"abstract":[{"type":"text","text":"Class for model loading and prediction"}],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileNetV2"}],"url":"\/documentation\/graffiti\/mobilenetv2"},"doc://com.tom.Graffiti/documentation/Graffiti":{"role":"collection","title":"Graffiti","abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","kind":"symbol","type":"topic","url":"\/documentation\/graffiti"},"doc://com.tom.Graffiti/documentation/Graffiti/kDEFAULT_XATTR_DELIM":{"role":"symbol","title":"kDEFAULT_XATTR_DELIM","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/kDEFAULT_XATTR_DELIM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}],"url":"\/documentation\/graffiti\/kdefault_xattr_delim"},"doc://com.tom.Graffiti/documentation/Graffiti/TagView":{"role":"symbol","title":"TagView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagView"}],"url":"\/documentation\/graffiti\/tagview"},"doc://com.tom.Graffiti/documentation/Graffiti/AnyOptional":{"role":"symbol","title":"AnyOptional","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnyOptional"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AnyOptional","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnyOptional"}],"url":"\/documentation\/graffiti\/anyoptional"},"doc://com.tom.Graffiti/documentation/Graffiti/SettingsView_Previews":{"role":"symbol","title":"SettingsView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsView_Previews"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/SettingsView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsView_Previews"}],"url":"\/documentation\/graffiti\/settingsview_previews"},"doc://com.tom.Graffiti/documentation/Graffiti/Sorter":{"role":"symbol","title":"Sorter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sorter"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Sorter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Sorter"}],"url":"\/documentation\/graffiti\/sorter"},"doc://com.tom.Graffiti/documentation/Graffiti/MobileNetV2Input":{"role":"symbol","title":"MobileNetV2Input","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MobileNetV2Input"}],"abstract":[{"type":"text","text":"Model Prediction Input Type"}],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/MobileNetV2Input","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MobileNetV2Input"}],"url":"\/documentation\/graffiti\/mobilenetv2input"},"doc://com.tom.Graffiti/documentation/Graffiti/ApplicationState":{"role":"symbol","title":"ApplicationState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ApplicationState"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ApplicationState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ApplicationState"}],"url":"\/documentation\/graffiti\/applicationstate"},"doc://com.tom.Graffiti/documentation/Graffiti/AppState":{"role":"symbol","title":"AppState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AppState"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AppState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AppState"}],"url":"\/documentation\/graffiti\/appstate"},"doc://com.tom.Graffiti/documentation/Graffiti/GraffitiApp":{"role":"symbol","title":"GraffitiApp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GraffitiApp"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/GraffitiApp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GraffitiApp"}],"url":"\/documentation\/graffiti\/graffitiapp"},"doc://com.tom.Graffiti/documentation/Graffiti/selectFile(ofTypes:callback:)":{"role":"symbol","title":"selectFile(ofTypes:callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ofTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UTType","preciseIdentifier":"s:22UniformTypeIdentifiers6UTTypeV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> ())"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/selectFile(ofTypes:callback:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/selectfile(oftypes:callback:)"},"doc://com.tom.Graffiti/documentation/Graffiti/FormatOption":{"role":"symbol","title":"FormatOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FormatOption"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FormatOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FormatOption"}],"url":"\/documentation\/graffiti\/formatoption"},"doc://com.tom.Graffiti/documentation/Graffiti/os_log(_:log:type:_:)":{"role":"symbol","title":"os_log(_:log:type:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"os_log"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"log"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Log","preciseIdentifier":"s:8Graffiti3LogO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Type","preciseIdentifier":"s:8Graffiti4TypeO"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/os_log(_:log:type:_:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/os_log(_:log:type:_:)"},"doc://com.tom.Graffiti/documentation/Graffiti/createOwnedImageURL()":{"role":"symbol","title":"createOwnedImageURL()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createOwnedImageURL"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/createOwnedImageURL()","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/createownedimageurl()"},"doc://com.tom.Graffiti/documentation/Graffiti/TPData(contentsOf:)":{"role":"symbol","title":"TPData(contentsOf:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"TPData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"contentsOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TPData(contentsOf:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/tpdata(contentsof:)"},"doc://com.tom.Graffiti/documentation/Graffiti/AddTagTransaction":{"role":"symbol","title":"AddTagTransaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddTagTransaction"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AddTagTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddTagTransaction"}],"url":"\/documentation\/graffiti\/addtagtransaction"},"doc://com.tom.Graffiti/documentation/Graffiti/FileWriter":{"role":"symbol","title":"FileWriter","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileWriter"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/FileWriter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FileWriter"}],"url":"\/documentation\/graffiti\/filewriter"},"doc://com.tom.Graffiti/documentation/Graffiti/TagStore":{"role":"symbol","title":"TagStore","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagStore"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagStore","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagStore"}],"url":"\/documentation\/graffiti\/tagstore"},"doc://com.tom.Graffiti/documentation/Graffiti/CompressedCustomTagStoreWriter":{"role":"symbol","title":"CompressedCustomTagStoreWriter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompressedCustomTagStoreWriter"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/CompressedCustomTagStoreWriter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CompressedCustomTagStoreWriter"}],"url":"\/documentation\/graffiti\/compressedcustomtagstorewriter"},"doc://com.tom.Graffiti/documentation/Graffiti/RemoveTagTransaction":{"role":"symbol","title":"RemoveTagTransaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RemoveTagTransaction"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/RemoveTagTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoveTagTransaction"}],"url":"\/documentation\/graffiti\/removetagtransaction"},"doc://com.tom.Graffiti/documentation/Graffiti/jsonify(tag:)":{"role":"symbol","title":"jsonify(tag:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"jsonify"},{"kind":"text","text":"("},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Tag","preciseIdentifier":"s:8Graffiti3TagC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/jsonify(tag:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/jsonify(tag:)"},"doc://com.tom.Graffiti/documentation/Graffiti/Log":{"role":"symbol","title":"Log","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Log"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Log","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Log"}],"url":"\/documentation\/graffiti\/log"},"doc://com.tom.Graffiti/documentation/Graffiti/ContentView":{"role":"symbol","title":"ContentView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentView"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/ContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"url":"\/documentation\/graffiti\/contentview"},"doc://com.tom.Graffiti/documentation/Graffiti/AddTagToManyFilesTransaction":{"role":"symbol","title":"AddTagToManyFilesTransaction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddTagToManyFilesTransaction"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/AddTagToManyFilesTransaction","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AddTagToManyFilesTransaction"}],"url":"\/documentation\/graffiti\/addtagtomanyfilestransaction"},"doc://com.tom.Graffiti/documentation/Graffiti/TagBackend":{"role":"symbol","title":"TagBackend","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TagBackend"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/TagBackend","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TagBackend"}],"url":"\/documentation\/graffiti\/tagbackend"},"doc://com.tom.Graffiti/documentation/Graffiti/selectFolder(callback:)":{"role":"symbol","title":"selectFolder(callback:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectFolder"},{"kind":"text","text":"("},{"kind":"externalParam","text":"callback"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"]) -> ())"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/selectFolder(callback:)","kind":"symbol","type":"topic","url":"\/documentation\/graffiti\/selectfolder(callback:)"},"doc://com.tom.Graffiti/documentation/Graffiti/Type":{"role":"symbol","title":"Type","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Type"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/Type","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Type"}],"url":"\/documentation\/graffiti\/type"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge"]},{"title":"Variables","identifiers":["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/kDEFAULT_XATTR_DELIM"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/title","value":"XattrBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/fragments","value":[{"kind":"identifier","text":"XattrBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1kDEFAULT_XATTR_DELIM\/title","value":"kDEFAULT_XATTR_DELIM"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1kDEFAULT_XATTR_DELIM\/fragments","value":[{"kind":"identifier","text":"kDEFAULT_XATTR_DELIM"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}