{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getXAttrAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delimitedBy"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delim"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/graffiti\/xattrbridge\/getxattrattributes(forfile:withkey:delimitedby:anderror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/graffiti\/xattrbridge\/getxattrattributes(forfile:withkey:delimitedby:anderror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getXAttrAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delimitedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)XattrBridge(cm)getXAttrAttributesForFile:withKey:delimitedBy:andError:","modules":[{"name":"Graffiti"}],"navigatorTitle":[{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}]},"hierarchy":{"paths":[["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge"]]},"references":{"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)":{"role":"symbol","title":"getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getXAttrAttributes"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forFile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delimitedBy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> ["},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/getXAttrAttributes(forFile:withKey:delimitedBy:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/getxattrattributes(forfile:withkey:delimitedby:anderror:)"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge":{"role":"symbol","title":"XattrBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XattrBridge"}],"url":"\/documentation\/graffiti\/xattrbridge"},"doc://com.tom.Graffiti/documentation/Graffiti":{"role":"collection","title":"Graffiti","abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","kind":"symbol","type":"topic","url":"\/documentation\/graffiti"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSArray","preciseIdentifier":"c:objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"getXAttrAttributesForFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"path"},{"kind":"text","text":" "},{"kind":"identifier","text":"withKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"delimitedBy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"delim"},{"kind":"text","text":" "},{"kind":"identifier","text":"andError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttributes(forFile:withKey:delimitedBy:andError:)\/title","value":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1getXAttrAttributes(forFile:withKey:delimitedBy:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"getXAttrAttributesForFile:withKey:delimitedBy:andError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/title","value":"XattrBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/fragments","value":[{"kind":"identifier","text":"XattrBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}