{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setXAttrAttributeForFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"path"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueOf"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/graffiti\/xattrbridge\/setxattrattributeforfile(_:valueof:withkey:anderror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/graffiti\/xattrbridge\/setxattrattributeforfile(_:valueof:withkey:anderror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/setXAttrAttributeForFile(_:valueOf:withKey:andError:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setXAttrAttributeForFile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"setXAttrAttributeForFile(_:valueOf:withKey:andError:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)XattrBridge(cm)setXAttrAttributeForFile:valueOf:withKey:andError:","modules":[{"name":"Graffiti"}],"navigatorTitle":[{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}]},"hierarchy":{"paths":[["doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge"]]},"references":{"doc://com.tom.Graffiti/documentation/Graffiti":{"role":"collection","title":"Graffiti","abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti","kind":"symbol","type":"topic","url":"\/documentation\/graffiti"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge":{"role":"symbol","title":"XattrBridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"XattrBridge"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"XattrBridge"}],"url":"\/documentation\/graffiti\/xattrbridge"},"doc://com.tom.Graffiti/documentation/Graffiti/XattrBridge/setXAttrAttributeForFile(_:valueOf:withKey:andError:)":{"role":"symbol","title":"setXAttrAttributeForFile(_:valueOf:withKey:andError:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setXAttrAttributeForFile"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"valueOf"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"andError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSErrorPointer","preciseIdentifier":"s:10Foundation14NSErrorPointera"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.tom.Graffiti\/documentation\/Graffiti\/XattrBridge\/setXAttrAttributeForFile(_:valueOf:withKey:andError:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}],"url":"\/documentation\/graffiti\/xattrbridge\/setxattrattributeforfile(_:valueof:withkey:anderror:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"setXAttrAttributeForFile:valueOf:withKey:andError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"setXAttrAttributeForFile:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"path"},{"kind":"text","text":" "},{"kind":"identifier","text":"valueOf:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"withKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"andError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["macOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/title","value":"XattrBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge\/fragments","value":[{"kind":"identifier","text":"XattrBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1setXAttrAttributeForFile(_:valueOf:withKey:andError:)\/title","value":"setXAttrAttributeForFile:valueOf:withKey:andError:"},{"op":"replace","path":"\/references\/doc:~1~1com.tom.Graffiti~1documentation~1Graffiti~1XattrBridge~1setXAttrAttributeForFile(_:valueOf:withKey:andError:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"setXAttrAttributeForFile:valueOf:withKey:andError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}